name: Tip Request
description: Request a GitHub Tip from MishManners
title: "[Tip]: I want "
labels: [Tip, enhancement]
assignees:
  - mishmanners
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking Mish for a Tip. Tune into a Live stream or read Mish's articles on DEV for great GitHub tips.
  - type: input
    id: Name
    attributes:
      label: Name of GitHub Tip
      description: What is the name of this GitHub Tip?
      placeholder: ex. GitHub Issue Forms
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: More information
      description: Add more information on the tip you would like to see.
      render: shell
    validations:
      required: true

  - type: dropdown
    id: Level
    attributes:
      label: What kind of level is this tip?
      description: What level of developer do you tthink this tip is aimed at?
      options:
        - Beginner
        - Intermediate
        - Advanced
    validations:
      required: true

  - type: checkboxes
    id: location
    attributes:
      label: Where do you want this GitHub Tip?
      description: Where would you like to see this GitHub Tip? You can select more than one.
      options:
        - label: Twitch
          required: false
        - label: DEV post
          required: false
        - label: YouTube video (longer)
          required: false
        - label: Twitter video (shorter)
          required: false
Click "Start commit":

Commit

Add a commit message if you like and click "Commit changes". If the code above is working (feel free to copy and paste mine to compare) there shouldn't be any errors when you committed the code. Read more about the types of syntax required for GitHub Issue Forms over on the GitHub Docs. If you have an error 🔴, skip step 4, and jump down to the "HELP 🔴" step.

Step 4. Fill out your form
Your form should now be complete! Now to test it:

Go to the repository where you made the template
Click the "Issues" tab
Click "New Issue"
Select the issue template you just created.
Mine is called "Tip Request" since this was the I have under name: in my template file.

Click "Get Started" and your issue form should be displayed.

This is what mine looks like:

GitHub Issue Form

You can see all the elements in the form that were added into the file. You can see the red asterisk * next to required fields.

Check out this form and match it up to the code aboveabove.

Step HELP 🔴 Get GitHub to help you build the form
One thing I love about GitHub Issue Forms is that if you get stuck building your template, GitHub is pretty good at helping you. For example, if you commit your code and you forgot to add a certain element, GitHub will give you an error, such as this:

Body error

This error means that the forth element in my form (body[4]) is missing one of its options. If we go back and compare the code, I can see that the forth element is the checkboxes at the end of the form and they don't have any options:

Code body4

All I need to do is add the options like this:

Error fix

If all this sounds really scary, or you're not sure where to start, or how to fix errors, GitHub can help. When you're creating your template, on the right hand side, you'll see some options to help you:

options

This handy configuration helper provides information on what needs to be included in the yaml file. There are code snippets to copy and paste and lots of information. It makes building these issue forms much easier and has helpful explanations about all the fields.

GitHub Issue Forms are still in beta
As of right now (August 2021), GitHub Issue forms are still in beta.

If you're reading this and issue templates are still in beta, then you might notice a Beta tag when you were creating the yaml file. Feedback is always super welcome and I promise the GitHub team reads every single piece of feedback and all suggestions.

If you'd like to give feedback on GitHub Issue forms, or any other feature, visit our Discussions Feedback.

How will you be using GitHub issues?

Git Good (9 Part Series)
1
Using the GitHub CLI to update your repo
2
How to create and pin a gist on GitHub
...
5 more parts...
8
How to use GitHub Pages to host your website, even with multiple repos
9
How to create a Profile README for your Organisation
Discussion (2)
Subscribe
pic
Add to the discussion
 
alexweininger profile image
Alex Weininger
•
Aug 11 '21

This is so freaking cool!


2
 likes
Reply
 
markgoho profile image
Mark Goho
•
Aug 17 '21

WOW! 🤯


1
 like
Reply
Code of Conduct • Report abuse
Read next
daniloab profile image
How to keep your repo package dependencies up to date automatically
Danilo Assis - Feb 10

santosh profile image
Automate HTTPS Certificates with Ansible Roles ft. Let's Encrypt & CloudFlare
Santosh Kumar - Feb 5

melcor76 profile image
Angular Error Interceptor
Michael Karén - Feb 14

ilya_azovtsev profile image
How to use JavaScript feature toggles to deploy safely [React.js example with Dev.to App]
Ilya Azovtsev - Feb 15


GitHub
Follow
More from GitHub
Three steps to better account security
#security #github #ato #webdev
Deploying My Probot App to a Serverless Lambda
#github #aws #tutorial #devops
Automating GitHub Org Invitations
#github #devops #opensource #tutorial
name: Tip Request
description: Request a GitHub Tip from MishManners
title: "[Tip]: I want "
labels: [Tip, enhancement]
assignees:
  - mishmanners
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking Mish for a Tip. Tune into a Live stream or read Mish's articles on DEV for great GitHub tips.
  - type: input
    id: Name
    attributes:
      label: Name of GitHub Tip
      description: What is the name of this GitHub Tip?
      placeholder: ex. GitHub Issue Forms
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: More information
      description: Add more information on the tip you would like to see.
      render: shell
    validations:
      required: true

  - type: dropdown
    id: Level
    attributes:
      label: What kind of level is this tip?
      description: What level of developer do you tthink this tip is aimed at?
      options:
        - Beginner
        - Intermediate
        - Advanced
    validations:
      required: true

  - type: checkboxes
    id: location
    attributes:
      label: Where do you want this GitHub Tip?
      description: Where would you like to see this GitHub Tip? You can select more than one.
      options:
        - label: Twitch
          required: false
        - label: DEV post
          required: false
        - label: YouTube video (longer)
          required: false
        - label: Twitter video (shorter)
          required: false
